name: CI
on: [push, pull_request]
jobs:
  run:
    strategy:
      matrix:
        include:
          - php: '7.4'
          - php: '8.0'
          - php: '8.1'
          - php: '8.2'
          - php: '8.3'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: pcov

      - name: Install dependencies
        uses: ramsey/composer-install@v4

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml --log-junit junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: junit.xml

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: phpstan
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4

      - name: Run PHPStan
        run: phpstan analyse --no-progress
